version: "3"

services:
  # Service Gladys Assistant
  gladys:
    image: gladysassistant/gladys:v4
    container_name: gladys
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gladys_data:/var/lib/gladysassistant
    environment:
      - NODE_ENV=production
      - TZ=Afrique/Abidjan
    depends_on:
      - mosquitto

  # Service Broker MQTT (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_log:/mosquitto/log

  # Client MQTT Python pour envoyer des données simulées
  mqtt-client:
    build:
      context: ./mqtt-client
      dockerfile: Dockerfile
    container_name: mqtt-client
    restart: always
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME= # Utilisateur (vide = pas d'authentification)
      - MQTT_PASSWORD= # Mot de passe (vide = pas d'authentification)
      - MQTT_CLIENT_ID=gladys_sensor_client
      - PUBLISH_INTERVAL=60

# Définition des volumes persistants
volumes:
  gladys_data:
  mosquitto_data:
  mosquitto_log:
